name: Auto tag on merge

on:
  pull_request:
    branches: [ master, main ]
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-tag:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: Shigure-Ruiseki/OK-Actions-Workflows/.github/workflows/auto-tag.yml@master
    with:
      branch: ${{ github.event.pull_request.base.ref || github.ref_name }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
